### ISSUE TITLE
Can't manage to run the program

### ISSUE THREAD

**Issue by another-sapiens** [gopher64/gopher64#27]
Hello there. 
Yesterday I installed this app as a flatpak, and unfortunately it didn't open. I've tried running it from the terminal using `flatpak run io.github.gopher64.gopher64`, but no luck. What's strange is that there is no output, no errors, even using arguments such as `--help` or `--version`.

Of course, it could be an issue on my end, so I should probably ask first: Are there any requirements to run the program? Perhaps something should be installed on my machine?

Thank you for your attention.

**Comment by loganmc10** [comment]
The program requires a CPU that supports AVX2 instructions (basically an Intel 4xxx model or newer), besides that I can't think of any hard requirements

**Comment by another-sapiens** [comment]
Yes, I just checked and my CPU does not seem to support AVX2, so that's probably it.
If there's a way for the app to detect this, it could be a good idea to inform the user.

Again, thanks for your attention and quick response.
