### ISSUE TITLE
Can't build on Linux.

### ISSUE THREAD

**Issue by io3432iooivzs** [gopher64/gopher64#65]
Hi.

I'd tried to build v0.1.6 on Linux (Debian12/bookworm).
But failed, build stopped with under error messages.

=== Error messages from ===

   Compiling typenum v1.17.0
   Compiling rustix v0.38.34
error: failed to run custom build command for `typenum v1.17.0`

Caused by:
  process didn't exit successfully: `{MY_HOME_DIR}/gopher64-0.1.6/target/release/build/typenum-40ca016cb72a8397/build-script-main` (signal: 4, SIGILL: illegal instruction)
  --- stdout
  cargo:rerun-if-changed=build/main.rs
warning: build failed, waiting for other jobs to finish...

=== Error messages here ===

I'd tried some solutions,maybe.

1) Add typenum before building.
$ cd gopher64-0.1.6
$ cargo add typenum

2) Add system typenum libraries.
$ sudo apt install librust-typenum-dev

3) Specified Clang-15 instead of Debian12 default (Clang-14).
$ export CC=clang-15
$ export CXX=clang++-15

But these methods only returned same error messages. Can't solve problem.
What wrong?

**Comment by loganmc10** [comment]
You can try changing or removing this line:

https://github.com/gopher64/gopher64/blob/d644617d623c322b3074390f4a1779bd0b96ee54/.cargo/config.toml#L2

You can try changing it to `target-cpu=x86-64-v2`, it's possible that your computer doesn't support v3

**Comment by io3432iooivzs** [comment]
Thanks reply, and success to build!
But v0.1.6 was building failed, otherwise, Today's git clone was building success.

Boot gopher64 to success also, I played some game a while, speed was too slow :-<
mupen64plus + parallel-RDP plugin was playing speed fine, almost games I have.
I'll post my PC specs.

A8-7600
Radeon R7 graphics(internal CPU)
A88XM-A

Only exits a few emulators for to play N64,
I'll counting on gopher64.
